### ISSUE TITLE
Planning to implement WAM2 API support

### ISSUE THREAD

**Issue by micahscopes** [webaudiomodules/webdx7#9]
Hey, I just wanted to share that I intend to implement WAM2 support soon.  Please let me know if you have any ideas about this or if there is anything you think I ought to keep in mind!

**Comment by micahscopes** [comment]
By the way, I recently joined the Web Audio slack workspace if you'd like to chat there.  [Here is the invite link](https://web-audio-slackin.herokuapp.com)

**Comment by jariseon** [comment]
very cool! while at it, can you maybe also take a look at embind to make processor.cpp/h API more approachable from JS side? i'm unsure if ccalls/cwraps still offer performance benefits over embind. at least control rate calls should be just fine with embind.

**Comment by micbuffa** [comment]
Hey @micahscopes If you still plan to do this, let me know.... Maybe I can help as I proposed a project to my Master Students consisting in porting the old @jariseon synths to WAM2.

**Comment by micahscopes** [comment]
@micbuffa I must admit that I just haven't had the bandwidth to follow through on this :weary:

If any of your master students are interested I'd say go for it.  This is an awesome project that would benefit from a WAM2 interface.  I'm glad to help if there's any way I possibly can!  Feel free to ping me on the Web Audio slack if you'd like to connect me with anyone.

**Comment by micbuffa** [comment]
I'll keep you informed....
